name: Reusable Android Distribution

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string

jobs:
  android-distribution:
    runs-on: diary-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref }}

      - name: Build Setup
        uses: ./.github/actions/build-setup

      - name: Secret Setup
        uses: ./.github/actions/secret-setup
        with:
          local-properties: ${{ secrets.LOCAL_PROPERTIES }}
          dev-debug-xcconfig: ${{ secrets.DEV_DEBUG_XCCONFIG }}
          dev-release-xcconfig: ${{ secrets.DEV_RELEASE_XCCONFIG }}
          real-debug-xcconfig: ${{ secrets.REAL_DEBUG_XCCONFIG }}
          real-release-xcconfig: ${{ secrets.REAL_RELEASE_XCCONFIG }}
          dev-google-services-json: ${{ secrets.DEV_GOOGLE_SERVICES_JSON }}
          real-google-services-json: ${{ secrets.REAL_GOOGLE_SERVICES_JSON }}
          dev-debug-google-services-info: ${{ secrets.DEV_DEBUG_GOOGLE_SERVICES_INFO }}
          real-release-google-services-info: ${{ secrets.REAL_RELEASE_GOOGLE_SERVICES_INFO }}

      - name: Build APK
        run: ./gradlew :app:assembleRealRelease --no-build-cache --no-configuration-cache -Pbuildkonfig.flavor=real

      - name: Firebase App Distribution
        uses: emertozd/Firebase-Distribution-Github-Action@v2
        with:
          appId: ${{ secrets.ANDROID_REAL_RELEASE_FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_KEY }}
          groups: Developer,Android
          file: app/build/outputs/apk/real/release/app-real-release.apk
          releaseNotesFile: CHANGELOG.md