name: Check Test

on:
  pull_request:

jobs:
  jvm-test:
    runs-on: diary-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Runtime Setup
        uses: ./.github/actions/build-setup
        with:
          java-version: '21'
          java-distribution: 'temurin'
          android-sdk: 'true'

      - name: Secret Setup
        uses: ./.github/actions/secret-setup
        with:
          local-properties: ${{ secrets.LOCAL_PROPERTIES }}
          dev-debug-xcconfig: ${{ secrets.DEV_DEBUG_XCCONFIG }}
          dev-release-xcconfig: ${{ secrets.DEV_RELEASE_XCCONFIG }}
          real-debug-xcconfig: ${{ secrets.REAL_DEBUG_XCCONFIG }}
          real-release-xcconfig: ${{ secrets.REAL_RELEASE_XCCONFIG }}
          dev-google-services-json: ${{ secrets.DEV_GOOGLE_SERVICES_JSON }}
          real-google-services-json: ${{ secrets.REAL_GOOGLE_SERVICES_JSON }}
          dev-debug-google-services-info: ${{ secrets.DEV_DEBUG_GOOGLE_SERVICES_INFO }}
          real-release-google-services-info: ${{ secrets.REAL_RELEASE_GOOGLE_SERVICES_INFO }}

      - name: Test JVM
        run: ./gradlew jvmTest --no-build-cache --no-configuration-cache
